name: CI / CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run flake8
        uses: py-actions/flake8@v2
  
  build_and_push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - id: commit_hash
        run: echo "::set-output name=commit_hash::${GITHUB_SHA::7}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }}

  deploy:
    strategy:
      matrix:
        host: [54.154.155.164, 54.152.72.31]
    name: Deploy on servers
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      USERNAME: ubuntu
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Deploy to EC2 instances via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ matrix.host }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          envs: DOCKER_USER, DOCKERHUB_TOKEN
          port: 22
          script: |

            export TAG=${{ needs.build_and_push.outputs.commit_hash }}
         
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker compose -f ~/flaskapp/docker-compose.yml down
            docker compose -f ~/flaskapp/docker-compose.yml up -d
            docker logout
  
  report:
    name: Make report
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Curl 54.154.155.164
        run: curl -i -X GET http://54.154.155.164:8000/api/health-check/ok

      - name: Curl 54.152.72.31
        run: curl -i -X GET http://354.152.72.31:8000/api/health-check/ok
